import { createServer as createHttpServer, type Server } from "node:http";
import { mkdtempSync, rmSync } from "node:fs";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { ConfigStore } from "../src/config.js";
import { createServer } from "../src/server.js";
import { applyResponseFilter } from "../src/filter.js";
import { isRestrictedAddress, validateTarget } from "../src/policy.js";
import { safeHeaderNames, writeAudit } from "../src/audit.js";
function payload(result: unknown): Record<string, any> { const text = (result as { content: Array<{ text: string }> }).content[0]?.text; return JSON.parse(text ?? "{}"); }
describe("http-mcp policy and bounded HTTP contract", () => {
  it("classifies loopback and private addresses", () => { expect(isRestrictedAddress("127.0.0.1")).toBe(true); expect(isRestrictedAddress("10.0.0.1")).toBe(true); expect(isRestrictedAddress("8.8.8.8")).toBe(false); expect(isRestrictedAddress("::1")).toBe(true); });
  it("rejects private targets unless explicitly enabled", async () => { await expect(validateTarget("http://127.0.0.1:1", { version: 1, allowedDomains: [], allowPrivateNetworks: false, allowHttp: true, allowHttps: true, maxResponseBytes: 1024, defaultTimeoutSeconds: 1, maxRedirects: 1, auditEnabled: false })).rejects.toMatchObject({ code: "policy_rejected" }); });
  it("always rejects the cloud metadata address", async () => { await expect(validateTarget("http://169.254.169.254/latest", { version: 1, allowedDomains: [], allowPrivateNetworks: true, allowHttp: true, allowHttps: true, maxResponseBytes: 1024, defaultTimeoutSeconds: 1, maxRedirects: 1, auditEnabled: false })).rejects.toMatchObject({ code: "policy_rejected" }); });
  it("classifies an unresolvable host as dns_failed", async () => { await expect(validateTarget("http://helix-test-host.invalid", { version: 1, allowedDomains: [], allowPrivateNetworks: false, allowHttp: true, allowHttps: true, maxResponseBytes: 1024, defaultTimeoutSeconds: 1, maxRedirects: 1, auditEnabled: false })).rejects.toMatchObject({ code: "dns_failed" }); });
  it("crops fields, arrays, and strings for model-safe output", () => { const result = applyResponseFilter({ keep: "abcdef", drop: true, rows: [1, 2, 3] }, { fields: ["keep", "rows"], arrayLimit: 2, maxStringBytes: 4 }); expect(result.value).toEqual({ keep: "abcd", rows: [1, 2] }); expect(result.truncated).toBe(true); });
  it("does not persist sensitive header names or query secrets in audit", async () => { const auditPath = path.join(os.tmpdir(), `helix-http-audit-${process.pid}-${Date.now()}.jsonl`); process.env.HELIX_HTTP_AUDIT_PATH = auditPath; try { expect(safeHeaderNames({ Authorization: "Bearer secret", Cookie: "session-secret", "X-API-Key": "api-secret", "X-Trace": "safe" })).toEqual(["X-Trace"]); await writeAudit({ version: 1, allowedDomains: [], allowPrivateNetworks: false, allowHttp: true, allowHttps: true, maxResponseBytes: 1024, defaultTimeoutSeconds: 1, maxRedirects: 1, auditEnabled: true }, { requestId: "audit-test", method: "GET", url: "https://example.test/resource?token=query-secret", headerNames: ["X-Trace"], durationMs: 1 }); const audit = await fs.readFile(auditPath, "utf8"); expect(audit).toContain("/resource"); expect(audit).not.toContain("query-secret"); expect(audit).not.toContain("Bearer secret"); } finally { delete process.env.HELIX_HTTP_AUDIT_PATH; rmSync(auditPath, { force: true }); } });
});
describe("http-mcp local HTTP E2E", () => {
  let tempDir: string; let listener: Server; let baseUrl: string; let client: Client; let server: ReturnType<typeof createServer>;
  beforeEach(async () => {
    tempDir = mkdtempSync(path.join(os.tmpdir(), "helix-http-mcp-"));
    listener = createHttpServer((request, response) => { if (request.url?.startsWith("/json")) { response.setHeader("content-type", "application/json"); response.end(JSON.stringify({ answer: 42, rows: [1, 2, 3], secret: "do-not-log" })); return; } if (request.url?.startsWith("/invalid-json")) { response.setHeader("content-type", "application/json"); response.end("not-json"); return; } if (request.url?.startsWith("/status")) { response.statusCode = 500; response.end("unavailable"); return; } if (request.url?.startsWith("/not-found")) { response.statusCode = 404; response.end("missing"); return; } if (request.url?.startsWith("/large")) { response.setHeader("content-type", "text/plain"); response.end("x".repeat(200)); return; } if (request.url?.startsWith("/redirect-external")) { response.statusCode = 302; response.setHeader("location", "https://example.com/private"); response.end(); return; } if (request.url?.startsWith("/redirect")) { response.statusCode = 302; response.setHeader("location", "/json"); response.end(); return; } if (request.url?.startsWith("/slow")) { setTimeout(() => response.end("late"), 300); return; } if (request.url?.startsWith("/echo")) { const chunks: Buffer[] = []; request.on("data", (chunk: Buffer) => chunks.push(chunk)); request.on("end", () => { response.setHeader("content-type", "application/json"); response.end(JSON.stringify({ method: request.method, query: request.url, body: Buffer.concat(chunks).toString("utf8") })); }); return; } response.setHeader("content-type", "text/plain"); response.end("hello"); });
    await new Promise<void>((resolve) => listener.listen(0, "127.0.0.1", resolve)); const address = listener.address(); if (!address || typeof address === "string") throw new Error("test server did not bind"); baseUrl = `http://127.0.0.1:${address.port}`;
    const store = new ConfigStore(path.join(tempDir, "config.json")); await fs.writeFile(store.filePath, JSON.stringify({ version: 1, allowedDomains: ["127.0.0.1"], allowPrivateNetworks: true, allowHttp: true, allowHttps: false, maxResponseBytes: 128, defaultTimeoutSeconds: 2, maxRedirects: 2, auditEnabled: false })); server = createServer(store); const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair(); client = new Client({ name: "http-test", version: "0.0.1" }); await server.connect(serverTransport); await client.connect(clientTransport);
  });
  afterEach(async () => { await client.close().catch(() => {}); await server.close().catch(() => {}); await new Promise<void>((resolve) => listener.close(() => resolve())); rmSync(tempDir, { recursive: true, force: true }); });
  it("performs GET text and JSON requests with filtering", async () => { const text = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/text` } })); expect(text.ok).toBe(true); expect(text.text).toBe("hello"); const json = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/json`, responseFilter: { fields: ["answer", "rows"], arrayLimit: 2 } } })); expect(json.ok).toBe(true); expect(json.data).toEqual({ answer: 42, rows: [1, 2] }); });
  it("performs JSON POST and preserves query parameters", async () => { const result = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/echo`, json: { hello: "world" }, query: { page: 2, verbose: true }, responseType: "json" } })); expect(result.ok).toBe(true); expect(result.data).toEqual({ method: "POST", query: "/echo?page=2&verbose=true", body: '{"hello":"world"}' }); });
  it("returns structured HTTP, JSON, timeout, redirect, and size errors", async () => { const invalid = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/invalid-json`, responseType: "json" } })); expect(invalid.error.code).toBe("invalid_json"); const status = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/status` } })); expect(status.error).toMatchObject({ code: "http_error", status: 500 }); const notFound = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/not-found` } })); expect(notFound.error).toMatchObject({ code: "http_error", status: 404 }); const timeout = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/slow`, timeoutSeconds: 0.1 } })); expect(timeout.error?.code).toBe("timeout"); const redirect = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/redirect-external` } })); expect(redirect.error?.code).toBe("redirect_rejected"); const large = payload(await client.callTool({ name: "http_request", arguments: { url: `${baseUrl}/large` } })); expect(large.error).toMatchObject({ code: "response_too_large", recommendedStrategy: "local_search" }); expect(large.byteLength).toBeGreaterThan(128); });
});
