import { applyResponseFilter } from "./filter.js";
import { newRequestId, redactUrl, safeHeaderNames, writeAudit } from "./audit.js";
import { RequestPolicyError, validateTarget } from "./policy.js";
import type { HttpConfig, HttpFailure, HttpRequestInput, HttpResult, HttpSuccess, ResponseType } from "./types.js";
function errorResult(input: { url: string; startedAt: number; code: HttpFailure["error"]["code"]; message: string; status?: number; contentType?: string | null; byteLength?: number; recommendedStrategy?: "local_search" | "ssh_strategy" }): HttpFailure { return { ok: false, url: input.url, elapsedMs: Date.now() - input.startedAt, ...(input.status === undefined ? {} : { status: input.status }), ...(input.contentType === undefined ? {} : { contentType: input.contentType }), ...(input.byteLength === undefined ? {} : { byteLength: input.byteLength }), error: { code: input.code, message: input.message, ...(input.status === undefined ? {} : { status: input.status }), ...(input.recommendedStrategy ? { recommendedStrategy: input.recommendedStrategy } : {}) } }; }
function classifyFetchError(error: unknown): { code: HttpFailure["error"]["code"]; message: string } { if (error instanceof RequestPolicyError) return { code: error.code, message: error.message }; if (error instanceof Error && error.name === "AbortError") return { code: "timeout", message: "request timed out" }; const cause = error instanceof Error && "cause" in error ? (error as Error & { cause?: NodeJS.ErrnoException }).cause : undefined; const code = cause?.code; if (code === "ENOTFOUND" || code === "EAI_AGAIN") return { code: "dns_failed", message: "DNS lookup failed" }; if (code?.startsWith("CERT") || code === "ERR_TLS_CERT_ALTNAME_INVALID" || code === "DEPTH_ZERO_SELF_SIGNED_CERT") return { code: "tls_failed", message: "TLS connection failed" }; return { code: "connection_failed", message: error instanceof Error ? error.message : String(error) }; }
async function readBounded(response: Response, maxBytes: number): Promise<{ bytes: Uint8Array; tooLarge: boolean; byteLength: number }> { if (!response.body) return { bytes: new Uint8Array(), tooLarge: false, byteLength: 0 }; const reader = response.body.getReader(); const chunks: Uint8Array[] = []; let total = 0; try { while (true) { const next = await reader.read(); if (next.done) break; total += next.value.byteLength; if (total > maxBytes) { await reader.cancel(); return { bytes: new Uint8Array(), tooLarge: true, byteLength: total }; } chunks.push(next.value); } } finally { reader.releaseLock(); } const bytes = new Uint8Array(total); let offset = 0; for (const chunk of chunks) { bytes.set(chunk, offset); offset += chunk.byteLength; } return { bytes, tooLarge: false, byteLength: total }; }
function chooseResponseType(contentType: string | null, requested: ResponseType | undefined): ResponseType { if (requested && requested !== "auto") return requested; return contentType?.toLowerCase().includes("json") ? "json" : "text"; }
function buildUrl(rawUrl: string, query: HttpRequestInput["query"]): URL { const url = new URL(rawUrl); for (const [key, value] of Object.entries(query ?? {})) url.searchParams.set(key, String(value)); return url; }
export async function executeHttpRequest(input: HttpRequestInput, config: HttpConfig): Promise<HttpResult> {
  const startedAt = Date.now(); const requestId = newRequestId(); const method = input.method ?? ((input.json !== undefined || input.body !== undefined) ? "POST" : "GET"); const headerNames = safeHeaderNames(input.headers); let currentUrl: URL;
  try { currentUrl = buildUrl(input.url, input.query); } catch { const result = errorResult({ url: input.url, startedAt, code: "policy_rejected", message: "url must be absolute" }); await writeAudit(config, { requestId, method, url: redactUrl(input.url), headerNames, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
  if (input.json !== undefined && input.body !== undefined) { const result = errorResult({ url: currentUrl.toString(), startedAt, code: "policy_rejected", message: "json and body are mutually exclusive" }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
  if ((input.json !== undefined || input.body !== undefined) && method === "GET") { const result = errorResult({ url: currentUrl.toString(), startedAt, code: "policy_rejected", message: "GET requests cannot include a body" }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
  const timeoutMs = Math.max(100, Math.min((input.timeoutSeconds ?? config.defaultTimeoutSeconds) * 1000, 300_000)); const maxBytes = Math.min(input.maxResponseBytes ?? config.maxResponseBytes, config.maxResponseBytes); const headers = new Headers(input.headers); let body: string | undefined;
  if (input.json !== undefined) { body = JSON.stringify(input.json); if (!headers.has("content-type")) headers.set("content-type", "application/json"); } else body = input.body;
  for (let redirects = 0; redirects <= config.maxRedirects; redirects += 1) {
    try { await validateTarget(currentUrl.toString(), config); } catch (error) { const classified = classifyFetchError(error); const code = redirects > 0 ? "redirect_rejected" : classified.code; const result = errorResult({ url: currentUrl.toString(), startedAt, code, message: redirects > 0 ? `redirect target rejected: ${classified.message}` : classified.message }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
    const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); let response: Response;
    try { response = await fetch(currentUrl, { method, headers, body, redirect: "manual", signal: controller.signal }); } catch (error) { clearTimeout(timer); const classified = classifyFetchError(error); const result = errorResult({ url: currentUrl.toString(), startedAt, code: classified.code, message: classified.message }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
    if (response.status >= 300 && response.status < 400) { const location = response.headers.get("location"); if (!location || redirects >= config.maxRedirects) { clearTimeout(timer); const result = errorResult({ url: currentUrl.toString(), startedAt, code: "redirect_rejected", message: "redirect target is missing or maximum redirects were exceeded", status: response.status }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, status: response.status, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; } try { currentUrl = new URL(location, currentUrl); } catch { clearTimeout(timer); const result = errorResult({ url: currentUrl.toString(), startedAt, code: "redirect_rejected", message: "redirect location is invalid", status: response.status }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, status: response.status, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; } clearTimeout(timer); continue; }
    const contentType = response.headers.get("content-type"); let bounded: { bytes: Uint8Array; tooLarge: boolean; byteLength: number };
    try { bounded = await readBounded(response, maxBytes); } catch (error) { clearTimeout(timer); const classified = classifyFetchError(error); const result = errorResult({ url: currentUrl.toString(), startedAt, code: classified.code, message: classified.message }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
    clearTimeout(timer);
    if (bounded.tooLarge) { const result = errorResult({ url: currentUrl.toString(), startedAt, code: "response_too_large", message: `response exceeded ${maxBytes} bytes`, status: response.status, contentType, byteLength: bounded.byteLength, recommendedStrategy: "local_search" }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, status: response.status, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
    const byteLength = bounded.byteLength; if (!response.ok) { const result = errorResult({ url: currentUrl.toString(), startedAt, code: "http_error", message: `HTTP ${response.status}`, status: response.status, contentType, byteLength }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, status: response.status, durationMs: result.elapsedMs, errorCode: result.error.code }); return result; }
    const text = new TextDecoder().decode(bounded.bytes); const responseType = chooseResponseType(contentType, input.responseType); const result: HttpSuccess = { ok: true, status: response.status, contentType, url: currentUrl.toString(), elapsedMs: Date.now() - startedAt, byteLength, truncated: false };
    if (responseType === "json") { let data: unknown; try { data = text.length ? JSON.parse(text) : null; } catch { const failure = errorResult({ url: currentUrl.toString(), startedAt, code: "invalid_json", message: "response content is not valid JSON", status: response.status, contentType, byteLength }); await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, status: response.status, durationMs: failure.elapsedMs, errorCode: failure.error.code }); return failure; } const filtered = applyResponseFilter(data, input.responseFilter); result.data = filtered.value; result.truncated = filtered.truncated; }
    else { const filtered = applyResponseFilter(text, input.responseFilter); result.text = typeof filtered.value === "string" ? filtered.value : JSON.stringify(filtered.value); result.truncated = filtered.truncated; }
    await writeAudit(config, { requestId, method, url: redactUrl(currentUrl.toString()), headerNames, status: response.status, durationMs: result.elapsedMs }); return result;
  }
  return errorResult({ url: currentUrl.toString(), startedAt, code: "redirect_rejected", message: "maximum redirects were exceeded" });
}
